name: Build

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.88.1'
                  extended: true

            - name: Clean public directory
              run: rm -rf public

            - name: Build site
              run: hugo

            - name: Deploy
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: public
